<a href="https://colab.research.google.com/github/SShyamili/python-libraries-basic-advanced/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

creating arrays

In [2]:
np.array([1,5,9])

array([1, 5, 9])

In [3]:
np.array([[1,2,3],[4,5,6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
np.array([[[4,5,6],[7,8,9]],[[1,2,3],[3,6,9]]])

array([[[4, 5, 6],
        [7, 8, 9]],

       [[1, 2, 3],
        [3, 6, 9]]])

In [5]:
np.array([[[4,5,6],[7,8,9]],[[1,2,3],[3,6,9]]],dtype=bool)

array([[[ True,  True,  True],
        [ True,  True,  True]],

       [[ True,  True,  True],
        [ True,  True,  True]]])

In [6]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(1,19).reshape(6,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [8]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [9]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.random.random((4,5))

array([[0.96117183, 0.25947182, 0.25039285, 0.13872979, 0.2768453 ],
       [0.13039749, 0.91768816, 0.18620613, 0.0034739 , 0.96545013],
       [0.8759799 , 0.69641925, 0.93527948, 0.30522026, 0.03993485],
       [0.27513679, 0.05464157, 0.5682013 , 0.31376334, 0.86476037]])

In [11]:
np.random.randint((4,5))

array([0, 3])

In [12]:
np.linspace(-2,5,10,dtype=int)

array([-2, -2, -1,  0,  1,  1,  2,  3,  4,  5])

In [13]:
a=np.identity(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array attributes


In [14]:
a=np.array([[1,2],[1.2,3.4]])
print(a.dtype)

float64


In [15]:
a.shape

(2, 2)

In [16]:
a.size

4

In [17]:
a.itemsize

8

In [18]:
a.ndim

2

In [19]:
a.dtype

dtype('float64')

In [20]:
a=np.arange(0,10,dtype=float)
a.dtype

dtype('float64')

changing data type

In [21]:
a.astype(int)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array operations


In [22]:
a1=np.arange(1,13).reshape(3*4)
a2=np.arange(13,25).reshape(3*4)


scalar operations


In [23]:
a1==a2

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [24]:
a1>a2

array([False, False, False, False, False, False, False, False, False,
       False, False, False])

In [25]:
a1<a2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [26]:
a1!=a2

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [27]:
a1*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24])

In [28]:
a1**2

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

vector operations

In [29]:
a1+a2

array([14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36])

In [30]:
a1-a2

array([-12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12, -12])

In [31]:
a1*a2

array([ 13,  28,  45,  64,  85, 108, 133, 160, 189, 220, 253, 288])

In [32]:
a1/a2

array([0.07692308, 0.14285714, 0.2       , 0.25      , 0.29411765,
       0.33333333, 0.36842105, 0.4       , 0.42857143, 0.45454545,
       0.47826087, 0.5       ])

array functions



In [33]:
a=np.random.random((1,5))

In [34]:
max(a)

array([0.42161937, 0.57463119, 0.05197468, 0.84755285, 0.17929131])

In [35]:
min(a)

array([0.42161937, 0.57463119, 0.05197468, 0.84755285, 0.17929131])

In [36]:
np.dot(a1,a2)

np.int64(1586)

In [37]:
np.exp(a1)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04, 5.98741417e+04, 1.62754791e+05])

In [38]:
a

array([[0.42161937, 0.57463119, 0.05197468, 0.84755285, 0.17929131]])

In [39]:
np.round(a)

array([[0., 1., 0., 1., 0.]])

In [40]:
np.floor(a)

array([[0., 0., 0., 0., 0.]])

In [41]:
np.ceil(a)

array([[1., 1., 1., 1., 1.]])

In [42]:
np.mean(a)

np.float64(0.4150138802475933)

In [43]:
np.var(a)

np.float64(0.07999477521973178)

In [44]:
np.median(a)

np.float64(0.4216193738450501)

In [45]:
a1[-1]

np.int64(12)

In [46]:
a1[1]

np.int64(2)

In [47]:
a

array([[0.42161937, 0.57463119, 0.05197468, 0.84755285, 0.17929131]])

In [48]:
a[0,:]

array([0.42161937, 0.57463119, 0.05197468, 0.84755285, 0.17929131])

In [49]:
a[:,0]

array([0.42161937])

In [50]:
a[1:,1:3]

array([], shape=(0, 2), dtype=float64)

In [51]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])

In [52]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [53]:
a=np.arange(1,13).reshape(3,4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
a[1,2]

np.int64(7)

In [55]:
a[::2,1::2]

array([[ 2,  4],
       [10, 12]])

In [56]:
a[0:2,0:3]

array([[1, 2, 3],
       [5, 6, 7]])

In [57]:
for i in a:
  print(i)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]


np.transpose(a)

In [58]:
np.transpose(a)

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [59]:
a.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [60]:
a.ravel()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [61]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [62]:
a.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [63]:
b=np.arange(1,13).reshape(3,4)

In [64]:
d=np.hstack((a,b))
d

array([[ 1,  2,  3,  4,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  5,  6,  7,  8],
       [ 9, 10, 11, 12,  9, 10, 11, 12]])

In [65]:
c=np.vstack((a,b))
c

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [66]:
np.hsplit(c,2)

[array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [ 1,  2],
        [ 5,  6],
        [ 9, 10]]),
 array([[ 3,  4],
        [ 7,  8],
        [11, 12],
        [ 3,  4],
        [ 7,  8],
        [11, 12]])]

time(performance analysis)


In [67]:
a=[i for i in range(100000)]
b=[i for i in range(100000,200000)]
c=[]
import time
start=time.time()
for i in range(len(a)):
  c.append(a[i]+b[i])
end=time.time()
print(end-start)

0.08729863166809082


memory

In [68]:
a=[i for i in range(100000)]
import sys
sys.getsizeof(a)

800984

In [69]:
a=np.arange(100000)
sys.getsizeof(a)

800112

In [70]:
a=np.arange(0,16).reshape(4,4)

In [71]:
a[[0,2,3]]

array([[ 0,  1,  2,  3],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [72]:
a[:,[0,2,]]

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14]])

In [73]:
b=np.random.randint(1,24,6)
b

array([15, 20, 12,  6,  2, 11])

In [74]:
b>50

array([False, False, False, False, False, False])

In [75]:
b<50

array([ True,  True,  True,  True,  True,  True])

In [76]:
b[b<20]

array([15, 12,  6,  2, 11])

In [77]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [78]:
(a>50) & (a%2==0)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [79]:
a[a%7!=0]

array([ 1,  2,  3,  4,  5,  6,  8,  9, 10, 11, 12, 13, 15])

In [80]:
a%7!=0

array([[False,  True,  True,  True],
       [ True,  True,  True, False],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])

In [81]:
a=np.arange(6).reshape(2,3)
b=np.arange(3).reshape(1,3)

In [87]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [88]:
b

array([[0, 1, 2]])

In [89]:
a+b

array([[0, 2, 4],
       [3, 5, 7]])

In [90]:
c=np.arange(1,3)
c

array([1, 2])

In [91]:
a+c

ValueError: operands could not be broadcast together with shapes (2,3) (2,) 

In [92]:
e=np.arange(10)

In [93]:
np.sum(e)

np.int64(45)

In [94]:
np.sin(a)

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 , -0.95892427]])

In [95]:
np.cos(a)

array([[ 1.        ,  0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362,  0.28366219]])

In [100]:
def sigmoid(array):
  return (1/1+np.exp(-(a)))
a=np.arange(100)
sigmoid(a)

array([2.        , 1.36787944, 1.13533528, 1.04978707, 1.01831564,
       1.00673795, 1.00247875, 1.00091188, 1.00033546, 1.00012341,
       1.0000454 , 1.0000167 , 1.00000614, 1.00000226, 1.00000083,
       1.00000031, 1.00000011, 1.00000004, 1.00000002, 1.00000001,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.        ,
       1.        , 1.        , 1.        , 1.        , 1.     

In [104]:
actual=np.random.randint(10,100,20)
predicted=np.random.randint(10,100,20)

In [106]:
def mse(actual,predicted):
  return np.mean((actual-predicted)**2)
mse(actual,predicted)


np.float64(600.55)

In [109]:
import time
start=time.time()
def mse(actual,predicted):
  return np.mean((actual-predicted)**2)
mse(actual,predicted)
print(start-time.time(),'sec')

-0.00046706199645996094 sec


In [110]:
a=np.array([1,2,3,np.nan,4,5])

In [111]:
np.isnan(a)

array([False, False, False,  True, False, False])

In [113]:
a[~np.isnan(a)]

array([1., 2., 3., 4., 5.])

In [115]:
a=actual=np.random.randint(10,100,20)

In [117]:
a

array([79, 95, 91, 20, 88, 53, 13, 41, 85, 44, 41, 47, 45, 18, 37, 52, 82,
       38, 85, 16])

In [116]:
np.sort(a)

array([13, 16, 18, 20, 37, 38, 41, 41, 44, 45, 47, 52, 53, 79, 82, 85, 85,
       88, 91, 95])

In [120]:
np.append(a,200)

array([ 79,  95,  91,  20,  88,  53,  13,  41,  85,  44,  41,  47,  45,
        18,  37,  52,  82,  38,  85,  16, 200])

In [121]:
b=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [122]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [126]:
np.append(b,np.ones((3,1)),axis=1)

array([[ 1.,  2.,  3.,  4.,  5.,  1.],
       [ 6.,  7.,  8.,  9., 10.,  1.],
       [11., 12., 13., 14., 15.,  1.]])

In [123]:
c=np.random.random((3,4))

In [124]:
c

array([[0.97166793, 0.24630088, 0.43039506, 0.55962312],
       [0.62416714, 0.47600968, 0.4204517 , 0.6258193 ],
       [0.75079521, 0.95675048, 0.24023081, 0.75418454]])

In [127]:
d=np.random.random((3,4))

In [128]:
d

array([[0.32553556, 0.46338289, 0.76353285, 0.20543606],
       [0.64952899, 0.93670829, 0.8613284 , 0.85839099],
       [0.66208678, 0.21732779, 0.30842212, 0.47734735]])

In [130]:
np.concatenate((c,c),axis=0)

array([[0.97166793, 0.24630088, 0.43039506, 0.55962312],
       [0.62416714, 0.47600968, 0.4204517 , 0.6258193 ],
       [0.75079521, 0.95675048, 0.24023081, 0.75418454],
       [0.97166793, 0.24630088, 0.43039506, 0.55962312],
       [0.62416714, 0.47600968, 0.4204517 , 0.6258193 ],
       [0.75079521, 0.95675048, 0.24023081, 0.75418454]])

In [131]:
np.concatenate((c,c),axis=1)

array([[0.97166793, 0.24630088, 0.43039506, 0.55962312, 0.97166793,
        0.24630088, 0.43039506, 0.55962312],
       [0.62416714, 0.47600968, 0.4204517 , 0.6258193 , 0.62416714,
        0.47600968, 0.4204517 , 0.6258193 ],
       [0.75079521, 0.95675048, 0.24023081, 0.75418454, 0.75079521,
        0.95675048, 0.24023081, 0.75418454]])

In [133]:
a

array([79, 95, 91, 20, 88, 53, 13, 41, 85, 44, 41, 47, 45, 18, 37, 52, 82,
       38, 85, 16])

In [132]:
np.unique(a)

array([13, 16, 18, 20, 37, 38, 41, 44, 45, 47, 52, 53, 79, 82, 85, 88, 91,
       95])

In [135]:
np.expand_dims(c,axis=1)

array([[[0.97166793, 0.24630088, 0.43039506, 0.55962312]],

       [[0.62416714, 0.47600968, 0.4204517 , 0.6258193 ]],

       [[0.75079521, 0.95675048, 0.24023081, 0.75418454]]])

In [136]:
np.expand_dims(c,axis=0)

array([[[0.97166793, 0.24630088, 0.43039506, 0.55962312],
        [0.62416714, 0.47600968, 0.4204517 , 0.6258193 ],
        [0.75079521, 0.95675048, 0.24023081, 0.75418454]]])

In [138]:
a

array([79, 95, 91, 20, 88, 53, 13, 41, 85, 44, 41, 47, 45, 18, 37, 52, 82,
       38, 85, 16])

In [137]:
np.where(a>20)

(array([ 0,  1,  2,  4,  5,  7,  8,  9, 10, 11, 12, 14, 15, 16, 17, 18]),)

In [141]:
np.where(a%2==0,0,a)

array([79, 95, 91,  0,  0, 53, 13, 41, 85,  0, 41, 47, 45,  0, 37,  0,  0,
        0, 85,  0])

In [143]:
np.argmax(a)

np.int64(1)

In [146]:
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [147]:
np.argmax(b,axis=1)

array([4, 4, 4])

In [148]:
np.argmax(b,axis=0)

array([2, 2, 2, 2, 2])

In [174]:
np.argmin(b,axis=1)

array([0, 0, 0])

In [150]:
a

array([79, 95, 91, 20, 88, 53, 13, 41, 85, 44, 41, 47, 45, 18, 37, 52, 82,
       38, 85, 16])

In [149]:
np.cumsum(a)

array([  79,  174,  265,  285,  373,  426,  439,  480,  565,  609,  650,
        697,  742,  760,  797,  849,  931,  969, 1054, 1070])

In [151]:
np.cumprod(a)

array([                  79,                 7505,               682955,
                   13659100,           1202000800,          63706042400,
               828178551200,       33955320599200,     2886202250932000,
         126992899041008000,  5206708860681328000,  4907643493798244992,
        -516971663593594752,  9141254129024846080,  6185009447147375872,
        8025841998601167872, -5963742768248092672, -5261296308912902144,
       -4488328488567443456,  1973720477759111168])

In [156]:
np.percentile(a,100)

np.float64(95.0)

In [157]:
np.histogram(a,bins=[0,10,20,30,40,50,60,70,80,90,100])

(array([0, 3, 1, 2, 5, 2, 0, 1, 4, 2]),
 array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100]))

In [159]:
np.corrcoef(c,d)

array([[ 1.        ,  0.72563868, -0.00300388, -0.43378056, -0.98201741,
         0.9802204 ],
       [ 0.72563868,  1.        ,  0.49148142, -0.92776878, -0.603863  ,
         0.83823284],
       [-0.00300388,  0.49148142,  1.        , -0.73170866,  0.04435297,
         0.07953204],
       [-0.43378056, -0.92776878, -0.73170866,  1.        ,  0.29912222,
        -0.57991813],
       [-0.98201741, -0.603863  ,  0.04435297,  0.29912222,  1.        ,
        -0.92604134],
       [ 0.9802204 ,  0.83823284,  0.07953204, -0.57991813, -0.92604134,
         1.        ]])

In [160]:
np.isin(a,[10,20,30])

array([False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False])

In [161]:
a[np.isin(a,[10,20])]

array([20])

In [162]:
np.flip(b,axis=0)

array([[11, 12, 13, 14, 15],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [163]:
np.flip(b,axis=1)

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

In [164]:
np.put(a,[0,1,2],[100,200,300])

In [165]:
np.delete(a,[0,1,2])

array([20, 88, 53, 13, 41, 85, 44, 41, 47, 45, 18, 37, 52, 82, 38, 85, 16])

In [166]:
m=np.array([1,2,3,4,5,])
n=np.array([5,6,7,8,9])

In [167]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [168]:
np.intersect1d(m,n)

array([5])

In [169]:
np.setdiff1d(m,n)

array([1, 2, 3, 4])

In [170]:
np.setdiff1d(n,m)

array([6, 7, 8, 9])

In [171]:
np.setxor1d(m,n)

array([1, 2, 3, 4, 6, 7, 8, 9])

In [172]:
np.in1d(m,n)

/tmp/ipython-input-172-207282267.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(m,n)


array([False, False, False, False,  True])

In [173]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 25, 75, 53, 25, 41, 75, 44, 41, 47, 45, 25, 37, 52, 75,
       38, 75, 25])